# Generated by Django 3.2.5 on 2021-07-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='block_user',
            field=models.ManyToManyField(blank=True, related_name='_accounts_user_block_user_+', to='accounts.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='user_groups', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_name='user_permission', to='auth.Permission'),
        ),
    ]
