# Generated by Django 3.2.5 on 2021-07-25 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210725_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='userProfile', serialize=False, to='accounts.user')),
                ('email_confirmation', models.BooleanField(default=False)),
                ('birth_date', models.DateField()),
                ('bio', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='dp')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
